sudo: required

arch:
  packages:
    - qt5-declarative
    - qt5-wayland
    - cmake
    - extra-cmake-modules
    - libdrm
    - mesa-libgl
    - wayland
    - wayland-protocols
    - libinput
    - libxkbcommon
    - xcb-util-cursor
    - libxcursor
    - xorg-server-xvfb
    - git
  script:
    - cmake . -DKDE_INSTALL_USE_QT_SYS_PATHS=ON -DCMAKE_INSTALL_PREFIX=/usr
    - make
    #- sudo make install
    #- xvfb-run -a -s "-screen 0 800x600x24" make check

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#hawaii-desktop
    use_notice: true
    skip_join: true
    on_success: always
    on_failure: change
  slack:
    secure: EGWF118PTfBj/Oktmr20fc17JTM5gt7/j24k6HkiOI1J8S+sJyxhhtSjV54cgmsaEURJ7zUD/xi2wSSigi82k2F29wpELInfty/+j95vuY+7QO7nyVIINHjKranLUogKai9evHU2cvlNTq6e27pjkDbRO2HNKyzTb+Lb6D3VEOk=
    on_success: always
    on_failure: change
